---

services:
  cycax_blender_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - DEVELOPMENT=true
      - DEBUG=false
    volumes:
      - .:/app
